---
title: "ODS_test query"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DBI)
library(tidyverse)
library(config)

# establish db connection locally
#con <- dbConnect(odbc::odbc(), .connection_string = 'driver={SQL Server};server={WSQ04151};database={ODS_test};trusted_connection=true')

# establish db connection for server
#con <- dbConnect(odbc::odbc(), .connection_string = 'driver={SQLServer};server={WSQ04151,50000};database={ODS_test};UID={rserver_read_only};PWD={m2TMJaRqD$m2TMJaRqD};trusted_connection=no')

# test server connection without trusted_connection statement bc dbConnect doesnt call for it
#con <- dbConnect(odbc::odbc(), .connection_string = 'driver={SQLServer};server={WSQ04151,50000};database={ODS_test};UID={rserver_read_only};PWD={m2TMJaRqD$m2TMJaRqD}')


con <- DBI::dbConnect(odbc::odbc(),
  Driver = "SQLServer", 
  Server= "WSQ04151,50000",
  Database = "ODS_test",
  UID = Sys.getenv("userid"),
  PWD = Sys.getenv("pwd")
)

print(con)
```


pull test data 

```{r}
dbGetQuery(con, "SELECT * FROM ODS_test.dbo.WQM_Stations_View WHERE Sta_ID = '1AGOO011.23' ") 
```


pull using dplyr

```{r}
tbl(con, "WQM_Stations_View") %>%
  filter(Sta_ID == '1AGOO011.23') %>%
  as_tibble() 
```

